### ISSUE TITLE
After importing the workflow, if the local model's name does not match the one in workflow, it will result in an error.

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#70]
The short-term solution is to import without loading the model in workflow. In the long run, we need to match the models with MD5

![Image](https://github.com/6174/comflowyspace/assets/37492595/02d4b2b9-86d6-40a2-89df-3572c3a46b0b)

**Comment by 6174** [comment]
Since we can't replace the error value or just hide the error value (if not exist user can download model by name).   What we can do is to visualize the error message to node, then user can understand the error and solve the problem

![Image](https://github.com/6174/comflowyspace/assets/3872872/3f204812-c82f-4844-8f06-03401a2d1f50)
